### ISSUE TITLE
最新版本出现以下问题

### ISSUE THREAD

**Issue by Junonin** [ciscochao/Xmind_Zen_Crack#2]
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    step1.del_all()
  File "C:\Program Files\XMind ZEN\crack.py", line 43, in del_all
    open(self.f_name, "wb").close()
FileNotFoundError: [Errno 2] No such file or directory: './resources/app/out/modal-activateAlert.js'

**Comment by gorquan** [comment]
新版的Xmind zen好像是去除了modal-activateAlert.js

**Comment by Gemsmith** [comment]
思科，我遇到了同样的错误，请您帮忙。

Traceback (most recent call last):
File "main.py", line 46, in
step1.del_all()
File "C:\Program Files\XMind ZEN\crack.py", line 43, in del_all
open(self.f_name, "wb").close()
FileNotFoundError: [Errno 2] No such file or directory: './resources/app/out/modal-activateAlert.js'

**Comment by ciscochao** [comment]
> 思科，我遇到了同样的错误，请您帮忙。
> 
> Traceback (most recent call last):
> File "main.py", line 46, in
> step1.del_all()
> File "C:\Program Files\XMind ZEN\crack.py", line 43, in del_all
> open(self.f_name, "wb").close()
> FileNotFoundError: [Errno 2] No such file or directory: './resources/app/out/modal-activateAlert.js'

目前该脚本仅支持在LINUX和MAC系统下的破解，看您的报错信息好像是在Windows环境下。

**Comment by ciscochao** [comment]
> Traceback (most recent call last):
> File "main.py", line 46, in
> step1.del_all()
> File "C:\Program Files\XMind ZEN\crack.py", line 43, in del_all
> open(self.f_name, "wb").close()
> FileNotFoundError: [Errno 2] No such file or directory: './resources/app/out/modal-activateAlert.js'

目前该脚本仅支持在LINUX和MAC系统下的破解，看您的报错信息好像是在Windows环境下。

**Comment by ciscochao** [comment]
> 新版的Xmind zen好像是去除了modal-activateAlert.js

**Comment by ciscochao** [comment]
> 新版的Xmind zen好像是去除了modal-activateAlert.js
关于新版本可以借鉴博文中提到的方法来自己动手~
https://www.cnblogs.com/4geek/p/11413865.html
